#version: '3.8'

services:
  agencia-viagens:
    image: agencia-viagens-image
    container_name: agencia-viagens-container
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - agencia-net

networks:
  agencia-net:
    driver: bridge
